# Generated by Django 6.1.1 on 2026-09-13 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام تجهیز')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد تجهیز')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='دسته\u200cبندی')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='موقعیت')),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('maintenance', 'در حال تعمیر'), ('broken', 'خراب')], default='active', max_length=20, verbose_name='وضعیت')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('warranty_expiry', models.DateField(blank=True, null=True, verbose_name='پایان گارانتی')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
            ],
            options={
                'verbose_name': 'تجهیز',
                'verbose_name_plural': 'تجهیزات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام قطعه')),
                ('part_number', models.CharField(max_length=50, unique=True, verbose_name='شماره قطعه')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='موجودی')),
                ('min_quantity', models.PositiveIntegerField(default=5, verbose_name='حداقل موجودی')),
                ('unit', models.CharField(default='عدد', max_length=20, verbose_name='واحد')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='محل ذخیره')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='تامین\u200cکننده')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'قطعه یدکی',
                'verbose_name_plural': 'قطعات یدکی',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان درخواست')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد'), ('critical', 'بحرانی')], default='medium', max_length=20, verbose_name='اولویت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('approved', 'تایید شده'), ('in_progress', 'در حال انجام'), ('completed', 'انجام شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('description', models.TextField(verbose_name='شرح مشکل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تکمیل')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='core.asset', verbose_name='تجهیز')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL, verbose_name='مسئول اجرا')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to=settings.AUTH_USER_MODEL, verbose_name='درخواست\u200cدهنده')),
            ],
            options={
                'verbose_name': 'درخواست تعمیر',
                'verbose_name_plural': 'درخواست\u200cهای تعمیر',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان دستور کار')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال انجام'), ('on_hold', 'متوقف'), ('closed', 'بسته')], default='open', max_length=20, verbose_name='وضعیت')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('estimated_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ساعت تخمینی')),
                ('actual_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='ساعت واقعی')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='work_order', to='core.maintenancerequest', verbose_name='درخواست')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to=settings.AUTH_USER_MODEL, verbose_name='تکنسین')),
            ],
            options={
                'verbose_name': 'دستور کار',
                'verbose_name_plural': 'دستورهای کار',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=200, verbose_name='اقدام انجام شده')),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='ساعات کار')),
                ('notes', models.TextField(blank=True, verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('technician', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تکنسین')),
                ('parts_used', models.ManyToManyField(blank=True, related_name='logs', to='core.sparepart', verbose_name='قطعات مصرفی')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.workorder', verbose_name='دستور کار')),
            ],
            options={
                'verbose_name': 'گزارش تعمیر',
                'verbose_name_plural': 'گزارشات تعمیر',
                'ordering': ['-created_at'],
            },
        ),
    ]
